package spl

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"
)

// CompileToGo generates a standalone Go function that renders the given template.
// The generated function has the signature:
//
//	func Render_<name>(data map[string]any) (string, error)
//
// It imports "github.com/oarkflow/spl" and uses the Render method internally.
// The generated code handles all template directives, expressions, and filters
// by embedding the template source and using the SPL runtime.
func (e *Engine) CompileToGo(name, tmpl string) ([]byte, error) {
	// Parse to validate
	compiled, err := e.compileStringTemplate(tmpl)
	if err != nil {
		return nil, fmt.Errorf("compile %q: %w", name, err)
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by spl.CompileToGo. DO NOT EDIT.\n\n")
	buf.WriteString("package main\n\n")
	buf.WriteString("import (\n\t\"github.com/oarkflow/spl\"\n)\n\n")

	// Generate the render function
	funcName := "Render_" + safeIdent(name)
	buf.WriteString(fmt.Sprintf("func %s(data map[string]any) (string, error) {\n", funcName))
	buf.WriteString(fmt.Sprintf("\tengine := spl.New()\n"))

	// Register any component definitions found in the template
	compNames := make([]string, 0, len(compiled.Components))
	for name := range compiled.Components {
		compNames = append(compNames, name)
	}
	sort.Strings(compNames)
	for _, cname := range compNames {
		def := compiled.Components[cname]
		body := renderNodesToSource(def.Body)
		buf.WriteString(fmt.Sprintf("\tengine.RegisterComponent(%q, %s)\n", cname, backtickString(body)))
	}

	// Embed the template source
	buf.WriteString(fmt.Sprintf("\ttmpl := %s\n", backtickString(tmpl)))

	buf.WriteString("\treturn engine.Render(tmpl, data)\n")
	buf.WriteString("}\n")

	// Format the generated code
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return buf.Bytes(), fmt.Errorf("format generated code: %w", err)
	}
	return formatted, nil
}

// CompileFileToGo compiles a template file to a Go function.
func (e *Engine) CompileFileToGo(name, path string) ([]byte, error) {
	resolved, err := e.resolvePath(path)
	if err != nil {
		return nil, fmt.Errorf("template file error (%s): %w", path, err)
	}
	compiled, err := e.compileFileTemplate(resolved)
	if err != nil {
		return nil, fmt.Errorf("template file error (%s): %w", path, err)
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by spl.CompileToGo. DO NOT EDIT.\n\n")
	buf.WriteString("package main\n\n")
	buf.WriteString("import (\n\t\"github.com/oarkflow/spl\"\n)\n\n")

	funcName := "Render_" + safeIdent(name)
	buf.WriteString(fmt.Sprintf("func %s(data map[string]any) (string, error) {\n", funcName))

	compNames := make([]string, 0, len(compiled.Components))
	for name := range compiled.Components {
		compNames = append(compNames, name)
	}
	sort.Strings(compNames)
	buf.WriteString(fmt.Sprintf("\tengine := spl.New()\n"))
	for _, cname := range compNames {
		def := compiled.Components[cname]
		body := renderNodesToSource(def.Body)
		buf.WriteString(fmt.Sprintf("\tengine.RegisterComponent(%q, %s)\n", cname, backtickString(body)))
	}

	buf.WriteString(fmt.Sprintf("\treturn engine.RenderFile(%q, data)\n", path))
	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return buf.Bytes(), fmt.Errorf("format generated code: %w", err)
	}
	return formatted, nil
}

// safeIdent converts an arbitrary string into a safe Go identifier.
func safeIdent(s string) string {
	var b strings.Builder
	for i, r := range s {
		if i == 0 {
			if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || r == '_' {
				b.WriteRune(r)
			} else {
				b.WriteRune('_')
			}
		} else {
			if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' {
				b.WriteRune(r)
			} else {
				b.WriteRune('_')
			}
		}
	}
	if b.Len() == 0 {
		return "_"
	}
	return b.String()
}

// backtickString wraps a string in Go raw backtick literals, escaping any backticks in the content.
func backtickString(s string) string {
	if !strings.ContainsRune(s, '`') {
		return "`" + s + "`"
	}
	// If the string contains backticks, use a concatenation of raw strings
	var b strings.Builder
	b.WriteString("`")
	for _, part := range strings.Split(s, "`") {
		b.WriteString(part)
		b.WriteString("` + \"`\" + `")
	}
	result := b.String()
	// Remove trailing " + \"`\" + `" if the string didn't end with a backtick
	result = strings.TrimSuffix(result, " + \"`\" + `")
	return result
}

// renderNodesToSource converts a node list back to template source code.
// This is used for embedding compiled component bodies in generated Go code.
func renderNodesToSource(nodes []Node) string {
	var b strings.Builder
	for _, n := range nodes {
		switch v := n.(type) {
		case *TextNode:
			b.WriteString(v.Text)
		case *ExprNode:
			b.WriteString("${")
			b.WriteString(v.Expr)
			for _, f := range v.Filters {
				b.WriteString(" | ")
				b.WriteString(f.Name)
				for _, a := range f.Args {
					b.WriteString(" ")
					b.WriteString(a)
				}
			}
			b.WriteString("}")
		case *IfNode:
			b.WriteString("@if(")
			for _, br := range v.Branches {
				b.WriteString(br.Cond)
			}
			b.WriteString(") { ... }")
		case *ForNode:
			b.WriteString("@for(...) { ... }")
		case *SlotNode:
			if v.Name != "" {
				b.WriteString("@slot(")
				b.WriteString(v.Name)
				b.WriteString(")")
			} else {
				b.WriteString("@slot")
			}
		default:
			b.WriteString("<!-- node -->")
		}
	}
	return b.String()
}
